/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2025-11-12T19:37:47.493Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Yvonne Quintero",
      photo: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761144514356-IMG_3500.jpeg",
      phone: "7134018283",
      email: "buyhomeswithyq@gmail.com",
      company: "LPT Realty, LLC",
      license: "RECO #84397152",
      repo: "New-Listing-376"
    },
    social: {
      instagram: "instagram.com/yvonne_htx_realtor",
      facebook: "Facebook.com/yvonnequinterorealtor",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: "https://linkedin.com/company/executivehomesrealtyinc"
    }
  };

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403945594-IMG_3522_hdr.jpg",
      alt: "Property image 1",
      category: "exterior"
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403946685-IMG_3549_hdr.jpg",
      alt: "Property image 2",
      category: "interior"
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403947107-IMG_3552_hdr.jpg",
      alt: "Property image 3",
      category: "interior"
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403947521-IMG_3564_hdr.jpg",
      alt: "Property image 4",
      category: "kitchen"
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403948124-IMG_3573_hdr.jpg",
      alt: "Property image 5",
      category: "bedroom"
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403948524-IMG_3579_hdr.jpg",
      alt: "Property image 6",
      category: "bedroom"
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403948963-IMG_3591_hdr.jpg",
      alt: "Property image 7",
      category: "bedroom"
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403949401-IMG_3597_hdr.jpg",
      alt: "Property image 8",
      category: "bathroom"
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403949784-IMG_3612_hdr.jpg",
      alt: "Property image 9",
      category: "exterior"
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403950303-IMG_3615_hdr.jpg",
      alt: "Property image 10",
      category: "exterior"
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403950783-IMG_3624.jpg",
      alt: "Property image 11",
      category: "exterior"
    }
  ];

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "3 Bedrooms",
      description: "The recent upgrades",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403945594-IMG_3522_hdr.jpg"
    },
    {
      id: "section2",
      title: "2 Bathrooms",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403946685-IMG_3549_hdr.jpg"
    },
    {
      id: "section3",
      title: "1816 SqFt",
      description: "Spacious living area with ample room for your lifestyle",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403947107-IMG_3552_hdr.jpg"
    },
    {
      id: "section4",
      title: "$$209,800",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403947521-IMG_3564_hdr.jpg"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Rose Marie",
    city: "Hearne",
    description: "Rose Marie is a quiet, small‑town neighborhood in Hearne rooted in the city's railroad legacy and wartime history. Residents benefit from easy access to US 79, US 190 and Texas State Highway 6, close proximity to Bryan/College Station and Texas A&M University, and a relaxed community lifestyle with local dining, parks and historic attractions.",
    highlights: [
      "Historic Hearne Railroad Depot, offering exhibits on local and railroad history",
      "Camp Hearne WWII Historic Site, featuring original POW camp foundations and artifacts",
      "Easy access to major highways (US 79, US 190, Texas State Highway 6) connecting to major Texas cities",
      "Small‑town charm with quality local dining, boutique shopping such as Tammy Kay’s Boutique, and parks for outdoor living"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "Tammy Kay’s Boutique",
      distance: "",
      category: "shopping",
      iconName: "ShoppingBag"
    },
    {
      id: 2,
      name: "Godfrey Gentry Park",
      distance: "",
      category: "recreation",
      iconName: "Leaf"
    },
    {
      id: 3,
      name: "Texas A&M University (Bryan/College Station area)",
      distance: "",
      category: "education",
      iconName: "School"
    },
    {
      id: 4,
      name: "Mi Casita Cafe",
      distance: "",
      category: "dining",
      iconName: "Coffee"
    },
    {
      id: 5,
      name: "The Oxtail Factory",
      distance: "",
      category: "dining",
      iconName: "Utensils"
    },
    {
      id: 6,
      name: "Hearne Cefco C Store",
      distance: "",
      category: "transportation",
      iconName: "Car"
    },
    {
      id: 7,
      name: "Crossroads of Texas Mural",
      distance: "",
      category: "recreation",
      iconName: "Users"
    },
    {
      id: 8,
      name: "US 79 / US 190 / Texas State Highway 6 (Highway access)",
      distance: "",
      category: "business",
      iconName: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "26/100",
      caption: "Car-Dependent",
      iconName: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "30/100",
      caption: "Some Transit",
      iconName: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "33/100",
      caption: "Somewhat Bikeable",
      iconName: "Compass",
      color: "bg-indigo-500"
    }
  ];

// openHouseBenefits configuration
export const openHouseBenefits = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 3 bedroom, 2 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Hearne.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "The district has a student-teacher ratio of 10 to 1 and serves students in grades PK-12.",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    nextDate: "Saturday, November 29, 2025",
    time: "2:00 PM - 4:00 PM",
    host: "Yvonne Quintero",
    phone: "7134018283",
    email: "buyhomeswithyq@gmail.com",
    ctaText: "RSVP for Open House",
    virtualTourAvailable: false,
    virtualTourUrl: "",
    allOpenHouses: [
      {
        date: "Saturday, November 29, 2025",
        time: "2:00 PM - 4:00 PM"
      }
    ]
  };

// packageItems configuration
export const packageItems = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 3 bedroom, 2 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Detached sales in Hearne.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "The district has a student-teacher ratio of 10 to 1 and serves students in grades PK-12.",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// property configuration
export const property = {
    name: "202 Rose Marie Blvd.",
    address: {
      street: "202 Rose Marie Blvd.",
      city: "Hearne",
      state: "Texas",
      zip: "77859",
      country: "United States"
    },
    price: "$209,800",
    beds: 3,
    baths: 2,
    sqft: 1816,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    type: "Detached",
    status: "For Sale",
    description: "Biggest lot on the block",
    shortDescription: "3 BEDS + 2 BATHS in Hearne",
    longDescription: "Biggest lot on the block, Recent Upgrades, Quiet Neighborhood",
    mainFeatures: [],
    propertyType: "Detached",
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403945594-IMG_3522_hdr.jpg",
    heroCaption: "Biggest Lot + Recent Upgrades + Quiet Neighborhood = Your Perfect Family Home Just Listed!"
  };

// propertyFeatures configuration
export const propertyFeatures = [
    "Qualifies for Hope Program/ 100% Financing"
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "/logo.svg",
    logoAlt: "202 Rose Marie Blvd.",
    favicon: "/favicon.ico",
    colors: {
      primary: "#D9A566",
      primaryDark: "#8B6839",
      primaryLight: "#E6C38C",
      dark: "#111111",
      light: "#FFFFFF"
    },
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403945594-IMG_3522_hdr.jpg",
    footer: {
      copyrightText: "© 2024 202 Rose Marie Blvd.. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change."
    }
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "202 Rose Marie Blvd. | Detached | Hearne",
    description: "Biggest Lot + Recent Upgrades + Quiet Neighborhood = Your Perfect Family Home Just Listed!",
    keywords: "detached, Hearne real estate, 3 bedroom, 2 bathroom, $209,800",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1762403945594-IMG_3522_hdr.jpg",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://202rosemarieblvd..com"
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Yvonne Quintero provided exceptional service and found us exactly what we were looking for in Hearne.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg"
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Yvonne Quintero presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg"
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Yvonne Quintero knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg"
    }
  ];

